[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:elasticsearch]
command=/usr/local/bin/docker-entrypoint.sh elasticsearch
user=elasticsearch
autostart=true
autorestart=true
stdout_logfile=/var/log/elasticsearch.log
stderr_logfile=/var/log/elasticsearch-error.log
priority=10

[program:backend]
command=node /app/backend/src/index.js
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend-error.log
environment=ES_NODE="http://localhost:9200",PORT="3001"
priority=20
startsecs=5

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx-access.log
stderr_logfile=/var/log/nginx-error.log
priority=30
